here::i_am("vignettes/precompile vignettes.R")

precompile_vignettes <- function() {
  knitr::knit(
    here::here("vignettes", "getting_started.Rmd.orig"),
    output = here::here("vignettes", "getting_started.Rmd"),
    envir = new.env()
  )

  knitr::knit(
    here::here("vignettes", "sentiment_analysis.Rmd.orig"),
    output = here::here("vignettes", "sentiment_analysis.Rmd"),
    envir = new.env()
  )
}

precompile_vignettes()

# # Include below answer_as_code chunk *after* compilation (in .Rmd):
# ![Plot generated by LLM](../man/figures/answer_as_code1-1.png)
# After sentiment plot:
# ![Plot of sentiment scores](../man/figures/plot_sentiment_analysis-1.png)

# if (FALSE) {
#   filename <- "man/figures/answer_as_code1-1.png"
#
#   # Construct local paths
#   local_paths <- c(
#     here::here(filename),
#     file.path(".", filename),
#     file.path("..", filename)
#   )
#
#   # Construct remote path
#   base_remote_url <- "https://github.com/tjarkvandemerwe/tidyprompt/blob/main"
#   remote_path <- file.path(base_remote_url, filename)
#
#   # Check each path in order and include the first one that exists
#   for (path in local_paths) {
#     if (file.exists(path)) {
#       knitr::include_graphics(path)
#       break
#     }
#   }
#
#   # If no local path exists, use the remote path
#   if (!any(sapply(local_paths, file.exists))) {
#     knitr::include_graphics(remote_path)
#   }
# }
